### ISSUE TITLE
It checks correctly, but it doesn't uncheck when issue is reopened

### ISSUE THREAD

**Issue by ambrt** [jonabc/sync-task-issues#12]
It seems it works in one way only (marking it when ref issue is closed) but not the other way around.

Can you look into it?
P.s. i'm on private repo so can't show example

**Comment by jonabc** [comment]
:wave: @ambrt I'll take a look.  Sorry for the delay in response, I missed the notification

**Comment by jonabc** [comment]
@ambrt I'm not sure what the issue is - it's working as expected with tests in this repo (feel free to close and reopen https://github.com/jonabc/sync-task-issues/issues/3, and check the status of the checkbox at https://github.com/jonabc/sync-task-issues/issues/4.

I know you're working from a private repo, but if you could include the configuration used when calling the action in this issue that would be very helpful.

**Comment by ambrt** [comment]
Thanks for comment. It is simple repo and only thing i have regarding actions is one file
`.github/workflows/cross-off.yml` in the root.
```
name: Cross off linked issues
on:
  issues:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cross of any linked issues
        uses: jonabc/sync-task-issues@v1
```

... ahh i think i see where the problem is.
In this repo you got workflow with
```
  issues:
    types: [closed, reopened]
  pull_request:
    types: [closed, reopened]
```
Was this earlier? I'm sure i was just copying workflow verbatim (from install action page of GH).

With this snippet it works both ways.
